// auto-generated
// Code generated by GUI builder.

package main

import (
	"image/color"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/canvas"
	"fyne.io/fyne/v2/container"
	"fyne.io/fyne/v2/layout"
	"fyne.io/fyne/v2/theme"
	"fyne.io/fyne/v2/widget"
)

type gui struct {
	win fyne.Window

	box      *canvas.Rectangle
	form     *widget.Form
	logo     *canvas.Image
	shutdown *widget.Button
	avatars  *fyne.Container
	bg       *fyne.Container
}

func newGUI() *gui {
	return &gui{}
}

func (g *gui) makeUI() fyne.CanvasObject {
	g.box = &canvas.Rectangle{FillColor: &color.NRGBA{R: 0xc, G: 0xc, B: 0xc, A: 0xaa}, StrokeColor: &color.NRGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x0}, StrokeWidth: 0, CornerRadius: 8}
	g.form = &widget.Form{Items: []*widget.FormItem{widget.NewFormItem("Password",
		&widget.Entry{Text: "", PlaceHolder: "", MultiLine: false, Password: true}), widget.NewFormItem("Session",
		widget.NewSelect([]string{"Option 1", "Option 2"}, func(s string) {}))}}
	g.logo = func() *canvas.Image {
		img := &canvas.Image{File: "/home/andy/Code/FyshOS/fin/assets/fysh.png", FillMode: canvas.ImageFillContain}
		img.SetMinSize(fyne.Size{Width: 82, Height: 82})
		return img
	}()
	g.shutdown = widget.NewButtonWithIcon("Shutdown", theme.CancelIcon(), g.shutdownTapped)
	g.avatars = container.NewGridWithRows(1,
		container.NewVBox(
			container.NewVBox(
				container.New(layout.NewCustomPaddedLayout(
					0,
					-8,
					0,
					0),
					func() *canvas.Image {
						img := &canvas.Image{Resource: theme.AccountIcon(), FillMode: canvas.ImageFillContain}
						img.SetMinSize(fyne.Size{Width: 112, Height: 112})
						return img
					}(),
					&canvas.Rectangle{FillColor: &color.NRGBA{R: 0x0, G: 0x0, B: 0x0, A: 0x0}, StrokeColor: &color.NRGBA{R: 0xc0, G: 0xc0, B: 0xc0, A: 0xff}, StrokeWidth: 2, CornerRadius: 0}),
				&widget.Label{Text: "user", TextStyle: fyne.TextStyle{Bold: true, Italic: false, Monospace: false, Symbol: false, TabWidth: 0, Underline: false}, Alignment: 1, Wrapping: 0})))
	g.bg = container.NewStack(
		canvas.NewImageFromResource(resourceBgDarkPng))

	return container.NewStack(
		g.bg,
		container.NewCenter(
			container.NewStack(
				g.box,
				container.NewStack(
					container.New(layout.NewCustomPaddedLayout(
						-368,
						0,
						96,
						96),
						g.logo)),
				container.New(layout.NewCustomPaddedLayout(
					42,
					42,
					42,
					42),
					container.NewBorder(
						nil,

						container.NewVBox(
							g.form,
							container.NewGridWithColumns(2,
								g.shutdown,
								&widget.Button{Text: "Log In", Importance: 1, Icon: theme.LoginIcon(), Alignment: 0, OnTapped: g.loginTapped})),
						nil,
						nil,
						&container.Scroll{
							Direction: container.ScrollHorizontalOnly,
							Content: container.NewCenter(
								g.avatars),
						})))))
}

func (g *gui) makeWindow(a fyne.App) fyne.Window {
	w := a.NewWindow("Fin")
	g.win = w
	w.Resize(fyne.NewSize(775, 476))
	w.SetPadded(false)
	w.SetContent(g.makeUI())
	return w
}
